version: '3.8' 

volumes:
  db:

services: 
  postgres:
    build: ./db
    image: postgres
    ports:
    - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
    - db:/var/lib/postgresql/data
    networks:
      - network_docker 
networks:
  network_docker:
    driver: bridge